// package main

// import (
// 	"bufio"
// 	"bytes"
// 	"fmt"
// 	"net/http"
// )

// // CustomSplit is a split function to tokenize input by sentences (ends with '.').
// func CustomSplit(data []byte, atEOF bool) (advance int, token []byte, err error) {
// 	// Look for the period character '.' as the end of a sentence.
// 	if i := bytes.IndexByte(data, '.'); i >= 0 {
// 		// Return the sentence as a token and include the period.
// 		return i + 1, data[:i+1], nil
// 	}
// 	// If at the end of file, return remaining data if it exists.
// 	if atEOF && len(data) > 0 {
// 		return len(data), data, nil
// 	}
// 	// Request more data.
// 	return 0, nil, nil
// }

// func main() {
// 	// Sends an HTTP GET request to "https://gobyexample.com"
// 	resp, err := http.Get("https://gobyexample.com")
// 	// Checks for errors in the HTTP request. If an error occurs, it panics and stops execution.
// 	if err != nil {
// 		panic(err)
// 	}
// 	// Ensures that the response body is closed after main() completes.
// 	defer resp.Body.Close()

// 	// Prints the HTTP response status (e.g., "200 OK")
// 	fmt.Println("Response status:", resp.Status)

// 	// Creates a new scanner to read the response body line-by-line.
// 	scanner := bufio.NewScanner(resp.Body)
// 	// we could use scanner.Split(bufio.ScanBytes) or scanner.Split(bufio.ScanWords) or scanner.Split(custom split function e.g. CustomSplit). But the default is scanner.Split(bufio.ScanLines)

// 	/*
// 		scanner.Scan():

// 		This method reads the next line or token from the input.
// 		It returns a boolean value: true if the scan was successful (i.e., if there is more content to read), and false if the scanner has reached the end of the input or encounters an error.
// 		When used in a loop, scanner.Scan() continues to read each line until it reaches the end of the input.
// 	*/
// 	/*
// 		In the context of bufio.Scanner in Go, a token is a piece or unit of the input that is read or processed each time scanner.Scan() is called. The term "token" generally refers to any manageable chunk of data that can be separated or parsed from the input stream.

// 		Default Tokenization
// 		By default, bufio.Scanner tokenizes input by lines. This means each call to scanner.Scan() reads up to the next newline character (\n), making each line of text the "token" or unit being processed.

// 		Custom Tokenization
// 		You can change what a "token" represents by setting a different split function for the scanner with scanner.Split(). For instance:

// 		Words: You could use bufio.ScanWords function to make each word (delimited by whitespace) a token.
// 		Bytes: You could use bufio.ScanBytes function to treat each byte as a token.
// 		Custom Split Functions: You can define a custom function to tokenize the input however you like.
// 	*/

// 	// Loops through the response body and prints them.
// 	for scanner.Scan() {
// 		/*
// 			scanner.Text():

// 			This method returns the most recent token generated by scanner.Scan() as a string.
// 			In this example, it retrieves each line of text from the HTTP response body (since the default split function for bufio.Scanner is by lines).
// 			You call scanner.Text() immediately after scanner.Scan() to get the current line or token that was just scanned.
// 		*/

// 		// 'scanner.Text()' retrieves the text of each line.
// 		fmt.Println(scanner.Text())
// 	}

// 	/*
// 		scanner.Err():

// 		This method returns the first non-nil error that was encountered by scanner.Scan().
// 		It's essential to check scanner.Err() after the scanning loop ends to confirm that the loop terminated because it reached the end of the input, rather than due to an error.
// 		If an error occurred during the scan, scanner.Err() will contain that error, allowing the program to handle it appropriately.
// 	*/

// 	// Checks for any error encountered during the scanning process.
// 	// If an error is found, it panics and stops execution.
// 	if err := scanner.Err(); err != nil {
// 		panic(err)
// 	}
// }
